version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16
  pre_build:
    commands:
      - ENV DEBIAN_FRONTEND noninteractive
      - go mod tidy
      - /bin/bash scripts/create_template.sh
      - apt-get update
      - apt-get -y install libgtk-3-dev
      - apt-get -y install libwebkit2gtk-4.0-dev
  build:
    commands:
      - echo Build started on `date`
      - cd src
      - GOOS=linux
      - GOARCH=amd64
      - go build -ldflags="-s -w" -o `pwd`/../SimpleWebView
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - SimpleWebView
